### ISSUE TITLE
Questions about _take_mml function

### ISSUE THREAD

**Issue by WenzhengZhang** [shmsw25/AmbigQA#19]
Hi,
Thanks for sharing your work! 
I'm a little confused about the  [_take_mml](https://github.com/shmsw25/AmbigQA/blob/50e46ff9e5de890ebe8560bab03cce99bdf3391e/codes/models/span_predictor.py#L93) function. Could you tell me the reason why you add `- 1e10 * (loss_tensor==0).float()` here? Thanks!

**Comment by shmsw25** [comment]
Thanks for asking. MML is supposed to calculate ![-log\sum_{y}P(y)](https://latex.codecogs.com/svg.latex?-log\sum_{y}P(y)) and computes the cross entropy loss based on it. In the implementation, `loss_tensor` contains the cross entropy loss for every `y` that is equivalent to ![-logP(y)](https://latex.codecogs.com/svg.latex?-logP(y)) So we put `-` and then `exp` to re-calculate `P(y)`, sum over the answer candidates, and then apply `log` and `-` again to convert it back to the valid cross entropy loss.

This doesn't explain `- 1e10 * (loss_tensor==0).float()` yet. The reason for this term is to remove the impact of dummy answers which losses are 0. (See [this line](https://github.com/shmsw25/AmbigQA/blob/50e46ff9e5de890ebe8560bab03cce99bdf3391e/codes/models/span_predictor.py#L81) for how it was set to zero.) If we simply use `exp`, these zeros will be converted to ones. So we want to give a large negative value to these before applying `exp` so that they will be zeros once `exp` is applied.

**Comment by WenzhengZhang** [comment]
> Thanks for asking. MML is supposed to calculate ![-log\sum_{y}P(y)](https://camo.githubusercontent.com/9485262098e8ad8e5d65d817f456eb7f699796dcadd8b69e7f31c4204563b34e/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e6c617465783f2d6c6f6725354373756d5f2537427925374450287929) and computes the cross entropy loss based on it. In the implementation, `loss_tensor` contains the cross entropy loss for every `y` that is equivalent to ![-logP(y)](https://camo.githubusercontent.com/bbc1814c52430e8ed43450b82afa3f4b949b0e030cee805764390e8aa035bbae/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e6c617465783f2d6c6f6750287929) So we put `-` and then `exp` to re-calculate `P(y)`, sum over the answer candidates, and then apply `log` and `-` again to convert it back to the valid cross entropy loss.
> 
> This doesn't explain `- 1e10 * (loss_tensor==0).float()` yet. The reason for this term is to remove the impact of dummy answers which losses are 0. (See [this line](https://github.com/shmsw25/AmbigQA/blob/50e46ff9e5de890ebe8560bab03cce99bdf3391e/codes/models/span_predictor.py#L81) for how it was set to zero.) If we simply use `exp`, these zeros will be converted to ones. So we want to give a large negative value to these before applying `exp` so that they will be zeros once `exp` is applied.

Thanks a lot for your reply!  It's very helpful for me.
